development:
  clients:
    default:
      use_utc: false
      use_activesupport_time_zone: true
      database: code_challenge_p2_development
      hosts:
        - localhost:27017


test:
  clients:
    default:
      use_utc: false
      use_activesupport_time_zone: true
      database: code_challenge_p2_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      use_utc: false
      use_activesupport_time_zone: true
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1